First/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'first'
urlpatterns = [
    path('',views.schaduleHome.as_view(),name='index'),
    path('flight_detail/<int:flight_id>/',views.DetailFlight,name='flight_detail'),
    path('add_Schadule/',views.add_Schadule,name='add_Schadule')
    # path('Flight_Detail/<str:origin>/<str:distination>/<int:nomber>/<date')
]

Flightio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('First.urls',namespace='Home')),

]

First/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.db.models.enums import Choices
from django.db.models.fields import BooleanField
from django.db.models.fields.related import create_many_to_many_intermediary_model
from django.forms import widgets

class Flight(models.Model):
    iranair = 'iranair'
    mahan = 'mahan'
    airtour = 'airtour'
    aseman = 'aseman'
    zagros = 'zagros'
    kish = 'kish'
    qeshm = 'qeshm'
    ata = 'ata'
    meraj = 'meraj'
    taban = 'taban'
    caspian='caspian'
    karoon = 'karoon'
    sepehran_ = "sepehran_"
    varesh='varesh'
    flypersia = 'flypersia'
    
    tehran='tehran'
    abadan='abadan'
    isfahan='isfahan'
    ahvaz='ahvaz'
    tabriz= 'tabriz'
    kish='kish'
    chabahar='chabahar'
    khoramabad='khoramabad'
    shiraz='shiraz'
    kermanshah='kermanshah'
    mashhad='mashhad'

    
    City=[
        (tehran,'tehran'),
        (abadan,'abadan'),
        (mashhad,"mash'had"),
        (shiraz,'shiraz'),
        (isfahan,'isfahan'),
        (chabahar,'chabahar'),
    ]
    
    Airline =[
        (iranair,'iranair'),(mahan,'mahan'),(airtour,'airtour'),(aseman,'aseman'),(zagros,'zagros'),(kish,'kish'),
        (qeshm,'qeshm'),(ata,'ata'),(meraj,'meraj'),(taban,'taban'),(caspian,'caspian'),(karoon,'karon'),(sepehran_,'sepehran'),
        (varesh,'varesh'),(flypersia,'flypersia'),

    ]
    Flight_Origin = models.CharField(max_length=30,choices=City,)
    Flight_Distination = models.CharField(max_length=30,choices=City)
    Flight_Airline = models.CharField(max_length=10,choices=Airline)
    Flight_Nomber = models.CharField(max_length=10)
    Flight_Date = models.DateField()
    Flight_Time = models.TimeField()
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True,null=True)
    # is_valid = BooleanField(default=False)
    schadule_Date = models.DateField()
    schadule_Time = models.TimeField()


    def __str__(self):
        return f'{self.Flight_Nomber} {self.Flight_Origin} to {self.Flight_Distination} in {self.Flight_Date} at {self.Flight_Time} '

# class schadule(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     FlightNo = models.CharField(max_length=10,)

First/forms.py
from django import forms
from django.forms import fields
from .models import Flight
from bootstrap_datepicker_plus import DatePickerInput
from django.forms import  DateTimeField, DateInput
from bootstrap_datepicker_plus.widgets import DatePickerInput

class AddSchaduleForm(forms.ModelForm):
    class Meta:
        model = Flight
        fields =('Flight_Origin','Flight_Distination','Flight_Airline','Flight_Nomber','Flight_Date','Flight_Time','schadule_Date','schadule_Time')

First/views.py
from django.forms.widgets import DateInput
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic.list import ListView
from django.utils.text import slugify 
from First.models import Flight
from django.views.generic import DetailView
from django.contrib import messages
from Flightio.settings import TIME_ZONE
from .models import Flight
from .forms import AddSchaduleForm



class schaduleHome(ListView):
    template_name = 'First/schadule.html'
    model = Flight #return all of class
    queryset = Flight.objects.filter() #object_list
    context_object_name = 'Flight' 
    ordering = ['-created']

def DetailFlight(request,flight_id):
    flight = get_object_or_404(Flight,pk=flight_id)
    
    return render(request,'First/detail_schadule.html',{'flight':flight})


def add_Schadule(request):    
    if request.method == 'POST':
        form = AddSchaduleForm(request.POST)
        if form.is_valid():
            new_schadule = form.save(commit=False)
            new_schadule.slug = slugify(f"{form.cleaned_data['Flight_Origin']}-{form.cleaned_data['Flight_Distination']}-{form.cleaned_data['Flight_Airline']}-{form.cleaned_data['Flight_Nomber']}-{form.cleaned_data['Flight_Date']}")            
            
            new_schadule.save()
            messages.success(request, 'submited')
            return redirect('first:index')
        else:
            messages.warning(request, 'ridi')

    else:
        form = AddSchaduleForm()
    return render(request,'First/add_Schadule.html', {'form':form} )

First/templates/First/add_schadule.html
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <title>{% block title %} {% endblock %}</title>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">

</head>
<body>
    
     <div class="jumbotron">     
        
        <p class="form-body">
            {% include 'inc/messages.html' %}
            {{ form.non_field_errors }}

                <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">مبدا</th>
                    <th scope="col">مقصد</th>
                    <th scope="col">ایرلاین</th>
                    <th scope="col">شماره پرواز</th>
                    <th scope="col">تاریخ پرواز</th>
                    <th scope="col">ساعت پرواز</th>
                    <th scope="col">تاریخ جدید</th>
                    <th scope="col">ساعت جدید</th>
                  </tr>
                </thead>
                
                <tbody >
                    <tr >
                      <form action="" method="post">
                        {% csrf_token %}
                      <th scope="row"  >{{ flight.id}}</th>
                        
                      <td >{{ form.Flight_Origin }}</td>
                      <td>{{ form.Flight_Distination }}</td>
                      <td>{{ form.Flight_Airline }}</td>
                      <td>{{ form.Flight_Nomber }}</td>
                      <td>{{ form.Flight_Date }}</td>
                      <td>{{ form.Flight_Time }}</td>
                      <td>{{ form.schadule_Date }}</td>
                      <td>{{ form.schadule_Time }}</td>
                    </tr>
                 
                  </tbody>
            
                </table>
                <input type="submit" value="submit" class="btn btn-primary">
               
            </form>
            


            </div>
          
            </p>
    </div>

</body>
</html>

First/templates/First/add_schadule01.html
{% extends 'base.html' %}


{% block title %} Add Schadule {% endblock %}

{% block content %}


    <div class="fomr form-body mx-5 ">
        <form action="" class="post">
            {% csrf_token %}
            
                <div class="form-group row">
                  <label for="inputEmail3" class="col-form-label">مبدا <br/>{{ form.Flight_Origin }}</label>
                  <div class="col-sm-10"></div>
                  <label for="inputEmail3" class="col-form-label">مقصد</label>
                  <div class="col-sm-10">{{ form.Flight_Distination }}</div>
                </div>

            {{form}}
            <input type="submit" value="submit" class="btn btn-primary">


        </form>


    </div>


{% endblock %}

First/templates/First/detail_schadule.html
{% extends 'base.html' %}

{% block title %} Detail {% endblock %}

{% block content %}

<br/>
<br/>
<br/>
<br/>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">مبدا</th>
        <th scope="col">مقصد</th>
        <th scope="col">ایرلاین</th>
        <th scope="col">شماره پرواز</th>
        <th scope="col">تاریخ پرواز</th>
        <th scope="col">ساعت پرواز</th>
        <th scope="col">ساعت ثبت تغییرات</th>
        <th scope="col">سازنده</th>
      </tr>
    </thead>
    
    <tbody>
        <tr>
          <th scope="row" >{{ flight.id}}</th>
          <td>{{ flight.Flight_Origin }}</td>
          <td>{{ flight.Flight_Distination }}</td>
          <td>{{ flight.Flight_Airline }}</td>
          <td>{{ flight.Flight_Nomber }}</td>
          <td>{{ flight.Flight_Date|date:"SHORT_DATE_FORMAT" }}</td>
          <td>{{ flight.Flight_Time|time:"H:i" }}</td>
          <td>{{ flight.created }}</td>
          <td>user</td>
        </tr>
        
      </tbody>
    </table>


{% endblock %}

First/templates/First/schadule.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block content %}
<div class=" mx-5">
    <a class="btn btn-primary" href="{% url 'first:add_Schadule' %}">
        ثبت تغییرات
    </a>
</div>
<table class="table table-striped mx-5 ">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">مبدا</th>
        <th scope="col">مقصد</th>
        <th scope="col">ایرلاین</th>
        <th scope="col">شماره پرواز</th>
        <th scope="col">تاریخ پرواز</th>
        <th scope="col">ساعت پرواز</th>
        <th scope="col">ساعت ثبت تغییرات</th>
        <th scope="col">سازنده</th>
      </tr>
    </thead>
    
    <tbody>
        <tr>
<form action="" method="POST">
  {% csrf_token %}

          {% for flight in Flight %}
          <a href=""><th scope="row" >{{ flight.id}}</th>
          <td><a href="{% url 'first:flight_detail' flight.id %}">{{ flight.Flight_Origin }}</a></td>
          <td>{{ flight.Flight_Distination }}</td>
          <td>{{ flight.Flight_Airline }}</td>
          <td>{{ flight.Flight_Nomber }}</td>
          <td>{{ flight.Flight_Date|date:"SHORT_DATE_FORMAT" }}</td>
          <td>{{ flight.Flight_Time|time:"H:i" }}</td>
          <td>{{ flight.created }}</td>
          <td>user</td>
        </a>
        </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </form>

{% endblock %}